apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: l2io6i205-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: l2io6i205-nodejs 
  name: l2io6i205-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: l2io6i205-nodejs 
